# Generated by Django 4.2.5 on 2023-10-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('population', models.IntegerField(default=0)),
            ],
        ),
    ]
