# Generated by Django 4.2.5 on 2023-11-11 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chorobesity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='valid_data',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('valid_data', models.BooleanField(default=False)),
                ('population', models.IntegerField(default=0)),
                ('obesity_percentage_afflicted', models.IntegerField(blank=True, default=0, null=True)),
                ('obesity_population_afflicted', models.IntegerField(blank=True, default=0, null=True)),
                ('diabetes_percentage_afflicted', models.IntegerField(blank=True, default=0, null=True)),
                ('diabetes_population_afflicted', models.IntegerField(blank=True, default=0, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='chorobesity.state')),
            ],
        ),
    ]
