# Generated by Django 4.2.5 on 2023-10-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chorobesity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='obesity_percentage_afflicted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='obesity_population_afflicted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='state',
            field=models.CharField(default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='county',
            name='type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
