# Generated by Django 4.2.5 on 2023-10-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chorobesity', '0002_county_obesity_percentage_afflicted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='county',
            old_name='id',
            new_name='name',
        ),
    ]
