# Generated by Django 4.2.5 on 2023-11-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chorobesity', '0002_state_valid_data_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='name',
        ),
        migrations.RemoveField(
            model_name='state',
            name='name',
        ),
        migrations.AddField(
            model_name='county',
            name='id',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='state',
            name='id',
            field=models.CharField(default='', max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='state',
            name='state_name',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
