# Generated by Django 4.2.5 on 2023-11-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chorobesity', '0003_remove_county_name_remove_state_name_county_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='state_name',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='county',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
    ]
