# Generated by Django 4.2.5 on 2023-11-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chorobesity', '0004_rename_state_name_state_state_alter_county_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='state',
            new_name='name',
        ),
    ]
