# Generated by Django 4.2.5 on 2023-11-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chorobesity', '0006_remove_state_id_alter_state_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='county',
            field=models.CharField(default='', max_length=20),
        ),
    ]
