# Generated by Django 4.2.5 on 2023-11-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chorobesity', '0007_county_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='county',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='county',
            name='id',
            field=models.CharField(default='', max_length=55, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='county',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
