# Generated by Django 4.2.5 on 2023-11-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chorobesity', '0008_alter_county_county_alter_county_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='mean_diabetes_percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='mean_obesity_percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
