# Generated by Django 4.2.5 on 2023-11-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chorobesity', '0009_state_mean_diabetes_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='std_diabetes_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='std_obesity_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='mean_diabetes_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='mean_obesity_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
